In [42]:
a = [23,4,5,6,8,6,98]
print(a)
import numpy as np
print(np.__version__)
type(a)
b = np.array(a)
b = a+15
print(b)

[23, 4, 5, 6, 8, 6, 98]
1.19.2


TypeError: can only concatenate list (not "int") to list

In [27]:
print(b)
type(b)

[23  4  5  6  8  6 98]


numpy.ndarray

In [45]:
a = np.array(b)

In [31]:
type(a)

numpy.ndarray

In [46]:
b = a+15
print(b)

[ 38  19  20  21  23  21 113]


In [47]:
b.shape

(7,)

In [37]:
b.dtype

dtype('int32')

In [40]:
c = [23,4,5,6,8,6,98]

In [43]:
type(c)

list

In [57]:
d = np.array([[1,2,3],[4,5,6]], dtype=complex)
print(d)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [58]:
d.shape

(2, 3)

In [67]:
e = np.array([[[1,2,3],[4,5,6]],[[2,3,4],[3,4,5]]])
print(e)

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [3 4 5]]]


In [71]:
e.shape

(2, 2, 3)

In [72]:
e = np.array([[1,2,3],[4,5,6],[2,3,4],[3,4,5]])
print(e)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [3 4 5]]


In [75]:
e.shape = (3,4)

In [76]:
print(e)

[[1 2 3 4]
 [5 6 2 3]
 [4 3 4 5]]
